export const data = [
    {
      id: 1,
      subject: "Weekly Team Meeting",
      sender: "John Doe",
      address: "john.doe@example.com",
      preview: "Let's discuss our progress this Friday at 2 PM.",
      timestamp: 1689375600,
      isUnread: true,
      isStarred: true,
      isSelected: false,
      detailUrl: "dnhsjkbbdhd",
      isDraft: true,
      isSpam: true,
      isDeleted: false,
      isArchived: false,
      labels: ["Work"],
      attachments: [
        {
          id: 1,
          name: "proposal.pdf",
          size: 1024,
          url: "path/to/proposal.pdf",
          type: "pdf",
        },
      ],
      cc: ["team.member@example.com"],
      bcc: [],
      body: "Let's discuss our progress this Friday at 2 PM. See you all there.",
      inReplyTo: [],
    },
    {
      id: 2,
      subject: "New Project Proposal",
      sender: "Jane Smith",
      address: "jane.smith@example.com",
      preview: `I've attached the new project proposal for your review. `,
      timestamp: 1689649200,
      isUnread: false,
      isStarred: false,
      isSelected: false,
      detailUrl: "dckjshbmkshhdoo",
      isDraft: false,
      isSpam: false,
      isDeleted: false,
      isArchived: false,
      labels: ["Important"],
      attachments: [
        {
          id: 2,
          name: "meeting_notes.docx",
          size: 102400, // 100 KB
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          url: "https://example.com/attachments/meeting_notes.docx",
        },
      ],
      cc: [],
      bcc: [],
      body: `Hi, I've attached the new project proposal for your review. Let me know your thoughts. <a href="http://abubalo.vercel.app">My portfolio</a>`,
      inReplyTo: [],
    },
    {
      id: 3,
      subject: "Lunch Catch-Up?",
      sender: "Michael Brown",
      address: "michael.brown@example.com",
      preview: "Hey, are you free for lunch tomorrow? Let me know!",
      timestamp: 1689930000,
      isUnread: true,
      isStarred: false,
      isSelected: false,
      detailUrl: "klshdfhsdlf",
      isDraft: true,
      isSpam: false,
      isDeleted: false,
      isArchived: false,
      labels: ["Personal"],
      attachments: [
        {
          id: 3,
          name: "financial_report.xlsx",
          size: 307200, // 300 KB
          type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          url: "https://example.com/attachments/financial_report.xlsx",
        },
      ],
      cc: [],
      bcc: [],
      body: "Hey, are you free for lunch tomorrow? Let me know!",
      inReplyTo: [],
    },
    {
      id: 4,
      subject: "Quarterly Financial Report",
      sender: "Emily White",
      address: "emily.white@example.com",
      preview: "The quarterly financial report is ready for review.",
      timestamp: 1690214400,
      isUnread: true,
      isStarred: false,
      isSelected: false,
      detailUrl: "aslkdfjwelk",
      isDraft: false,
      isSpam: true,
      isDeleted: true,
      isArchive: false,
      labels: ["Finance"],
      attachments: [
        {
          id: 4,
          name: "logo.png",
          size: 51200, // 50 KB
          type: "image/png",
          url: "https://example.com/attachments/logo.png",
        },
      ],
      cc: ["finance.team@example.com"],
      bcc: [],
      body: "The quarterly financial report is ready for review. Please find the attached document.",
      inReplyTo: [],
    },
    {
      id: 5,
      subject: "Team Outing Plan",
      sender: "Chris Green",
      address: "chris.green@example.com",
      preview: "Let's plan our team outing for next month. Suggestions?",
      timestamp: 1690462800,
      isUnread: true,
      isStarred: false,
      isSelected: false,
      detailUrl: "oiuwefhlwkj",
      isDraft: false,
      isSpam: false,
      isDeleted: false,
      isArchived: false,
      labels: ["Team"],
      attachments: [
        {
          id: 5,
          name: "presentation.pptx",
          size: 512000, // 500 KB
          type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          url: "https://example.com/attachments/presentation.pptx",
        },
      ],
      cc: ["team@example.com"],
      bcc: [],
      body: "Let's plan our team outing for next month. Any suggestions on locations or activities?",
      inReplyTo: [],
    },
  ]